#!/usr/bin/env bash
#
# dexit: system shutdown dialog
#
# Author: David J. Luco <davidjluco@gmail.com>

nb='#002b36'
nf='#93a1a1'
sb='#cb4b16'
sf='#fdf6e3'
prompt='Choose an option:'
dmenu_cmd=( dmenu -b -i -nb "$nb" -nf "$nf" -sb "$sb" -sf "$sf" -p "$prompt" )

cmd=$( echo -e "cancel\nlogout\nsuspend\nhibernate\nhybrid\nreboot\npoweroff" | \
	xargs -0 printf %b |  "${dmenu_cmd[@]}" )

case $cmd in
    cancel)
		exit 0
		;;
	poweroff)
        systemctl poweroff
        ;;
    reboot)
        systemctl reboot
        ;;
    suspend)
        systemctl suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
    hybrid)
        systemctl hybrid-sleep
        ;;
    logout)
		# find the appropriate logout command for the current wm
		if [[ -n "$(pgrep i3)" ]]; then # check for i3
			i3-msg exit
		elif [[ -n "$(pgrep dwm)" ]]; then # check for dwm
			killall dwm
		elif [[ -n "$(pgrep openbox-session)" ]]; then # check for openbox
			openbox --exit
		fi
        ;;
esac
